apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-deployments-role
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups: ["apps"]
    resources: [deployments"]
    verbs: ["list", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-deployments-binding
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ template "mosipfileserver.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: restart-deployments-role
  apiGroup: rbac.authorization.k8s.io
